services:
  frontend:
    build:
      context: .
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/portfolio
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=portfolio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
